server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance: 
    hostname: localhost

spring: 
  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
         uir: lb://user-service
         predicates: 
            - Path=/user/**
        - id: car-service
         uri: lb://car-service
         predicates:
            - Path=/car/**
        - id: bike-service
         uri: lb://bike-service
         predicates:
            - Path=/bike/**